// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { env } from "process";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    // Para migrations, use a conexão DIRECT do Neon (melhor/mais estável)
    url: env("DIRECT_URL") || env("DATABASE_URL"),
  },
});